[0.009s] Invoking command in '/home/krishsahni/ros2_ws/src/crazyswarm2/build/crazyflie_interfaces': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/krishsahni/ros2_ws/src/crazyswarm2/crazyflie_interfaces -DAMENT_CMAKE_SYMLINK_INSTALL=1 -DCMAKE_INSTALL_PREFIX=/home/krishsahni/ros2_ws/src/crazyswarm2/install/crazyflie_interfaces
[0.011s] Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 59, in build
    rc = await extension.build(
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 87, in build
    rc = await self._reconfigure(args, env)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 172, in _reconfigure
    completed = await run(
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 183, in run
    completed = await colcon_core_subprocess_run(
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 100, in run
    rc, _, _ = await _async_check_call(
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 154, in _async_check_call
    stdout_descriptor, stdout = pty.openpty()
  File "/usr/lib/python3.10/pty.py", line 34, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib/python3.10/pty.py", line 64, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices
